// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIEcJyvRdXIxgIqsSxVR4ocgT9KwH3G_s',
    appId: '1:981373035880:web:f473a604ab529bfffa22dd',
    messagingSenderId: '981373035880',
    projectId: 'yope-your-pet-e4df8',
    authDomain: 'yope-your-pet-e4df8.firebaseapp.com',
    storageBucket: 'yope-your-pet-e4df8.appspot.com',
    measurementId: 'G-51EPSD6PQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Cw5Vd1GOsEbQDb85qfdK0Isfkg7u0c0',
    appId: '1:981373035880:android:ccf7b0c96c85a14cfa22dd',
    messagingSenderId: '981373035880',
    projectId: 'yope-your-pet-e4df8',
    storageBucket: 'yope-your-pet-e4df8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKc95boIMe_YzbI5_xyqjp2eWTknuWrFY',
    appId: '1:981373035880:ios:f884bbe9e5eae8b0fa22dd',
    messagingSenderId: '981373035880',
    projectId: 'yope-your-pet-e4df8',
    storageBucket: 'yope-your-pet-e4df8.appspot.com',
    iosClientId: '981373035880-5085j7lq85k4ds15qrbntlncsp8jorl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.yopeYourpetSocialNetworking',
  );
}
